### ISSUE TITLE
xpra.org SSL error

### ISSUE THREAD

**Issue by jackusm** [bencawkwell/ansible-dwaffortress#3]
```
TASK: [xdummy | Fetch xorg.conf] **********************************************
failed: [localhost] => {"failed": true}
msg: SSL Certificate does not belong to www.xpra.org.  Make sure the url has a certificate that belongs to it or use validate_certs=False (insecure)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/xpra.retry

localhost                  : ok=8    changed=4    unreachable=0    failed=1
```

**Comment by bencawkwell** [comment]
Thanks for reporting this issue.

So a bit of further investigation this looks to be caused by https://github.com/ansible/ansible-modules-core/issues/1716.

Luckily there is a workaround I can make which will support python version < 2.7.9. It would be nice to not to use the workaround, but since the latest version of python on Ubuntu 14.04 is 2.7.6 (http://packages.ubuntu.com/trusty/python2.7), and Ubuntu 14.04 is supported until 2019, I think the workaround is justified. Commit will follow shortly.
